target "FreeGemasMac" do
  platform :osx, "10.12"
  
  pod "Gosu/Gosu", :path => "../../Gosu/Gosu", :inhibit_warnings => true
end

target "FreeGemas" do
  platform :ios, "9.3"
  
  pod "Gosu/Gosu", :path => "../../Gosu/Gosu", :inhibit_warnings => true
  pod "Gosu/GosuAppDelegateMain", :path => "../../Gosu/Gosu"
end
